[package]
name = "lucidstream-ges"
version = "0.1.0"
authors = ["Denis Tsai <denistsai@aetheras.io>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/dt665m/lucidstream-rs"
description = "Lucidstream eventstore implementation for www.eventstore.com"

[dependencies]
lucidstream = { path = "../lucidstream" }
uuid = { version = "0.8.1", features = ["serde", "v4", "v5"] }
eventstore = { version = "0.9.2" }
async-trait = "0.1.40"
thiserror = {version = "1.0" }
futures = "0.3.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
