[package]
name = "lucidstream-ges"
version = "0.1.0"
authors = ["Denis Tsai <dt665m@gmail.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/dt665m/lucidstream-rs"
description = "Lucidstream eventstore implementation for www.eventstore.com"

[dependencies]
lucidstream = { path = "../lucidstream" }

log = { version = "0.4" }
uuid = { version = "0.8", features = ["serde", "v4", "v5"] }
eventstore = { version = "0.9" }
async-trait = { version = "0.1" }
thiserror = { version = "1" }
futures = { version = "0.3" }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
