version: "3"

networks:
  local:

services:
  postgres:
    image: postgres:13
    container_name: postgres
    expose:
      - 5432/tcp
    ports:
      - 5432:5432
    environment:
      # POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_PASSWORD: 123456
    networks:
      - local

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    networks:
      - local
