version: '3'

networks:
    local:

services:
    eventstore:
        image: eventstore/eventstore:20.10.0-buster-slim
        container_name: eventstore
        environment:
            EVENTSTORE_DISABLE_HTTP_CACHING: 'true'
            EVENTSTORE_INSECURE: 'true'
            # this is for debugging / Admin UI.  Eventually will get depricated
            EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP: 'true'
        ports:
            - 2113:2113
        networks:
            - local

    eventstore-arm:
        image: ghcr.io/eventstore/eventstore:21.10.0-alpha-arm64v8
        container_name: eventstore
        environment:
            EVENTSTORE_DISABLE_HTTP_CACHING: 'true'
            EVENTSTORE_INSECURE: 'true'
            # this is for debugging / Admin UI.  Eventually will get depricated
            EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP: 'true'
        ports:
            - 2113:2113
        networks:
            - local

    postgres:
        image: postgres:13
        container_name: postgres
        expose:
            - 5432/tcp
        ports:
            - 5432:5432
        environment:
            # POSTGRES_PASSWORD: ${PGPASSWORD}
            POSTGRES_PASSWORD: 123456
        networks:
            - local

    adminer:
        image: adminer:latest
        container_name: adminer
        ports:
            - 8080:8080
        environment:
            ADMINER_DEFAULT_SERVER: postgres
        networks:
            - local


