version: '3'

networks:
    local:

services:
    eventstore:
        image: eventstore/eventstore:20.6.1-buster-slim
        container_name: eventstore
        environment:
            EVENTSTORE_DISABLE_HTTP_CACHING: 'true'
            EVENTSTORE_INSECURE: 'true'
            # this is for debugging / Admin UI.  Eventually will get depricated
            EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP: 'true'
        ports:
            - 2113:2113
        networks:
            - local
