[package]
name = "integration-tests"
version = "0.5.1"
authors = ["Denis Tsai <denistsai@aetheras.io>"]
edition = "2018"

[lib]
doctest = false
test = false

[dependencies]
lucidstream-ges = { path = "../lucidstream-ges" }
lucidstream = { path = "../lucidstream" }

async-trait = { version = "0.1" }
tokio = { version = "0.2.22", features = ["signal", "rt-core", "rt-threaded", "net", "stream", "time", "macros"] }
serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.57"
bytes = { version = "0.5" }

